[package]
name = "canparse"
version = "0.1.4"
authors = ["Jon Magnuson <jon.magnuson@gmail.com>"]
description = "A CAN signal and definition parser"
repository = "https://github.com/jmagnuson/canparse"
documentation = "https://docs.rs/canparse"
readme = "README.md"
keywords = ["can", "socketcan", "j1939", "dbc", "parser"]
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
name = "canparse"
path = "src/lib.rs"

[[bench]]
name = "pgnlibrary"
harness = false

[[bench]]
name = "socketcan"
harness = false
required-features = ["use-socketcan"]

[features]
default = []
use-socketcan = ["socketcan"]

[dependencies]
byteorder = "1.5"
encoding = "0.2"
enum_primitive = "0.1"
nom = "4.2"
socketcan = { version = "3.2", optional = true }

[dev-dependencies]
approx = "0.5"
criterion = "0.5"
lazy_static = "1.4"

[package.metadata.docs.rs]
features = ["use-socketcan"]

[badges]
travis-ci = { repository = "jmagnuson/canparse" }
codecov = { repository = "jmagnuson/canparse", branch = "master", service = "github" }
